locale: "en"
label: "English"
weight: 1
title: "hanhela.org"

params:
  displayName: "EN"
  isoCode: "en"
  rtl: false
  dateFormat: "2 January 2006"
  #logo: "img/logo.svg"
  description: "Personal site about Kubernetes, GitOps, Linux and cloud native infrastructure."
  author:
    name: "Antti Hanhela"
    image: "img/blowfish-avatar.png"
    headline: "Cloud native and DevOps enthusiast and a Linux nerd"
    bio: "Notes and practical writeups about Kubernetes, GitOps, Linux and cloud native infrastructure."
    links:
      - email: "mailto:antti@hanhela.org"
      - linkedin: "https://www.linkedin.com/in/your-profile/"
      - github: "https://github.com/antief"
      
      
  homepage:
    layout: custom
    showHighlights: true
    showHighlightItems: 3
    showRecent: false
    showRecentItems: 6
    showMoreLink: false
    showMoreLinkDest: "/posts/"
    cardView: true
    cardViewScreenWidth: false
