locale: "fi"
label: "Suomi"
weight: 2
title: "hanhela.org"

params:
  displayName: "FI"
  isoCode: "fi"
  rtl: false
  dateFormat: "02.01.2006"
  #logo: "img/logo.svg"
  description: "Henkilökohtainen sivusto Kubernetes-, GitOps-, Linux- ja cloud native -aiheista."
  author:
    name: "Antti Hanhela"
    image: "img/blowfish-avatar.png"
    headline: "Cloud native ja DevOps -intoilija ja Linux-nörtti"
    bio: "Muistiinpanoja ja käytännön kirjoituksia Kubernetesista, GitOpsista, Linuxista ja cloud native -infrasta."
    links:
      - email: "mailto:antti@hanhela.org"
      - linkedin: "https://www.linkedin.com/in/your-profile/"
      - github: "https://github.com/antief"
  homepage:
    layout: custom
    showHighlights: true
    showHighlightItems: 3
    showRecent: false
    showRecentItems: 6
    showMoreLink: false
    showMoreLinkDest: "/fi/posts/"
    cardView: true
    cardViewScreenWidth: false
