ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: site.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: site-example-com-tls
      hosts:
        - site.example.com

gateway:
  enabled: false
